config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('majestic.urls', namespace='majestic')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

majestic/urls.py
from django.urls import path
from . import views


app_name = 'majestic'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('services/vyshivka-na-kroe', views.vnkroe, name='vnkroe'),
    path('services/shevrony-i-nashivki', views.shevnash, name='shevnash'),
    path('services/vyshivka-na-gotovyh-izdeliyah', views.vngotizd, name='vngotizd'),
    path('services/cerkovnaya-vyshivka', views.cerkvysh, name='cerkvysh'),
    path('price/', views.price, name='price'),
    path('contacts/', views.contacts, name='contacts'),
    path('qna/', views.qna, name='qna'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
]

majestic/models.py
from django.db import models


class FeedbackMessage(models.Model):
    fullname = models.CharField(verbose_name='Полное имя', max_length=255)
    phone = models.CharField(verbose_name='Номер телефона', max_length=16)
    email = models.EmailField(verbose_name='Адрес почты')
    message = models.TextField(verbose_name='Сообщение')
    agreement = models.BooleanField(verbose_name='Согласие на обработку ПД')
    date_send = models.DateTimeField(verbose_name='Дата отправления заявки', auto_now_add=True)

    class Meta:
        verbose_name = 'Сообщение/Вопрос'
        verbose_name_plural = 'Сообщения/Вопросы'

    def __str__(self):
        return self.fullname

majestic/forms.py
from django import forms
from .models import FeedbackMessage


class FeedbackMessageForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(
                    attrs={'class': 'feedback__field',
                           'placeholder': 'Иванов Иван Иванович'}
                ))
    phone = forms.CharField(widget=forms.TextInput(
                    attrs={'class': 'feedback__field',
                           'placeholder': '+7 (900) 000 00 00'}
                ))
    email = forms.CharField(widget=forms.TextInput(
                    attrs={'class': 'feedback__field',
                           'placeholder': 'ivanov-ivan@ivanovich.ru'}
                ))
    message = forms.CharField(widget=forms.Textarea(
                    attrs={'class': 'feedback__textarea',
                           'placeholder': 'Текст сообщения или вопрос'}
                ))
    agreement = forms.BooleanField(widget=forms.CheckboxInput(
                    attrs={'class': 'feedback__checkbox _hidden'}
                ))

    class Meta:
        model = FeedbackMessage
        fields = [
            'fullname',
            'phone',
            'email',
            'message',
            'agreement',
        ]

majestic/views.py
from django.shortcuts import render
from .forms import FeedbackMessageForm


def home(request):
    return render(request, 'majestic/index.html')


def about(request):
    return render(request, 'majestic/about.html')


def services(request):
    return render(request, 'majestic/services.html')

def vnkroe(request):
    return render(request, 'majestic/services/vnkroe.html')

def shevnash(request):
    return render(request, 'majestic/services/shevnash.html')

def vngotizd(request):
    return render(request, 'majestic/services/vngotizd.html')

def cerkvysh(request):
    return render(request, 'majestic/services/cerkvysh.html')


def price(request):
    return render(request, 'majestic/price.html')


def qna(request):
    return render(request, 'majestic/qna.html')


def contacts(request):
    context = {
        'feedback': FeedbackMessageForm,
    }
    return render(request, 'majestic/contacts.html', context)

def privacy_policy(request):
    return render(request, 'majestic/privacy-policy.html')

majestic/templates/majestic/about.html
{% extends 'majestic/base.html' %}
{% load static %}


{% block meta_tags %}

{% endblock %}

{% block title %}
<title>
    О компании «Majestic»
</title>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'majestic/css/about.min.css' %}">
{% endblock %}


{% block content %}
<div class="page-headings content__headings">
    <h1 class="page-title page-headings__title">
        Наша компания
    </h1>
</div>
<!-- / end of page headings -->

<section class="about content__about">
    <p class="about__paragraph">
        Мы занимаемся нанесением логотипов на&nbsp;готовые или текстильные изделия и&nbsp;крой при&nbsp;помощи современного вышивального оборудования. Наша компания «Majestic» работает с&nbsp;2018 года. За 4 года мы смогли добиться неплохих результатов, но&nbsp;не&nbsp;стоим на&nbsp;месте, а&nbsp;продолжаем постоянно совершенствовать качество своей работы и&nbsp;развивать новые направления, на&nbsp;благо наших Клиентов.
    </p>
</section>
<!-- / end of about -->
{% endblock %}

majestic/templates/majestic/components/counters.html
<!-- Yandex.Metrika counter -->
<script
    type="text/javascript"> (function (m, e, t, r, i, k, a) { m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) }; m[i].l = 1 * new Date(); for (var j = 0; j < document.scripts.length; j++) { if (document.scripts[j].src === r) { return; } } k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a) })(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(92381643, "init", { clickmap: true, trackLinks: true, accurateTrackBounce: true }); </script>
<noscript>
    <div><img src="https://mc.yandex.ru/watch/92381643" style="position:absolute; left:-9999px;" alt="" /></div>
</noscript>
<!-- / Yandex.Metrika counter -->

majestic/templates/majestic/components/footer.html
<footer class="footer">
    <div class="footer-upside footer__upside">
        <div class="footer-navigation footer-upside__navigation">
            <a href="{% url 'majestic:home' %}" class="footer-navigation__item">
                Главная страница
            </a>
            <a href="{% url 'majestic:about' %}" class="footer-navigation__item">
                О компании
            </a>
            <a href="{% url 'majestic:price' %}" class="footer-navigation__item">
                Стоимость вышивки
            </a>
            <a href="{% url 'majestic:contacts' %}" class="footer-navigation__item">
                Контактная информация
            </a>
            <a href="{% url 'majestic:qna' %}" class="footer-navigation__item">
                Вопросы и ответы
            </a>
        </div>
        <!-- / end of 1st navigation column -->

        <div class="footer-navigation footer-upside__navigation">
            <a href="{% url 'majestic:services' %}" class="footer-navigation__item">
                Предоставляемые услуги
            </a>
            <a href="{% url 'majestic:vnkroe' %}" class="footer-navigation__item footer-navigation__item_opacity">
                Вышивка на крое
            </a>
            <a href="{% url 'majestic:shevnash' %}" class="footer-navigation__item footer-navigation__item_opacity">
                Шевроны и нашивки
            </a>
            <a href="{% url 'majestic:vngotizd' %}" class="footer-navigation__item footer-navigation__item_opacity">
                Вышивка на готовых изделиях
            </a>
            <a href="{% url 'majestic:cerkvysh' %}" class="footer-navigation__item footer-navigation__item_opacity">
                Церковная вышивка
            </a>
        </div>
        <!-- / end of 2nd navigation column -->

        <div class="footer-contacts footer-upside__contacts">
            <div class="fcontacts-item footer-contacts__item footer-contacts__item_half">
                <p class="fcontacts-item__name">
                    Хрустова Юлия
                </p>
                <p class="fcontacts-item__data">
                    +7 (930) 707 75 55
                </p>
            </div>
            <div class="fcontacts-item footer-contacts__item footer-contacts__item_half">
                <p class="fcontacts-item__name">
                    Каширина Татьяна
                </p>
                <p class="fcontacts-item__data">
                    +7 (920) 036 31 66
                </p>
            </div>
            <div class="fcontacts-item footer-contacts__item">
                <p class="fcontacts-item__name">
                    Адрес почты
                </p>
                <p class="fcontacts-item__data">
                    info@majestic.ru
                </p>
            </div>
            <div class="fcontacts-item footer-contacts__item">
                <p class="fcontacts-item__name">
                    Адрес офиса/производства
                </p>
                <p class="fcontacts-item__data">
                    Нижний Новгород, ул.Геологов 1Л
                </p>
            </div>
        </div>
        <!-- / end of footer contacts -->
    </div>
    <!-- / end of footer upside -->

    <div class="footer-downside footer__downside">
        <div class="footer-info footer-downside__info">
            <p class="footer-info__copyrights">
                &copy;2023. Вышивальная компания «Маджестик»
            </p>
            <div class="footer-links footer-info__links">
                <a href="{% url 'majestic:privacy-policy' %}" class="footer-links__item">
                    Политика конфиденциальности
                </a>
                <a href="{% url 'sitemap' %}" class="footer-links__item">
                    Карта сайта
                </a>
            </div>
        </div>
        <!-- / end of footer info -->

        <p class="footer-developers footer-downside__developers">
            Разработка сайта
            <a href="https://vk.com/zestify" target="_blank" class="footer-developers__link">
                Zestify
            </a>
        </p>
        <!-- / end of footer developers -->
    </div>
    <!-- / end of footer downside -->
</footer>

majestic/templates/majestic/components/header.html
{% load static %}
<header class="header wrapper__header" id="header">
    <div class="header-inner header__inner">
        <a href="{% url 'majestic:home' %}" class="header-inner__home">
            <img src="{% static 'logotype.png' %}" alt="" class="header-inner__logo">
        </a>
        <nav class="menu header-inner__menu">
            <a href="{% url 'majestic:about' %}" class="menu__link
            {% if request.path == '/about/' %}_active{% endif %}">
                О компании
            </a>
            <a href="{% url 'majestic:services' %}" class="menu__link
            {% if request.path == '/services/' %}_active{% endif %}">
                Наши услуги
            </a>
            <a href="{% url 'majestic:price' %}" class="menu__link
            {% if request.path == '/price/' %}_active{% endif %}">
                Стоимость вышивки
            </a>
            <a href="{% url 'majestic:qna' %}" class="menu__link
            {% if request.path == '/qna/' %}_active{% endif %}">
                Вопросы и ответы
            </a>
            <a href="{% url 'majestic:contacts' %}" class="menu__link
            {% if request.path == '/contacts/' %}_active{% endif %}">
                Контакты
            </a>
        </nav>
        <div class="header-info header-inner__info">
            <div class="header-socials header-info__socials">
                <a href="" class="header-socials__link" title="Viber, Хрустова Юлия">
                    <img src="{% static 'majestic/img/socials/viber.png' %}" alt="" class="header-socials__image">
                </a>
                <a href="" class="header-socials__link" title="WhatsApp, Хрустова Юлия">
                    <img src="{% static 'majestic/img/socials/whatsapp.png' %}" alt="" class="header-socials__image">
                </a>
                <a href="" class="header-socials__link" title="Telegram, Хрустова Юлия">
                    <img src="{% static 'majestic/img/socials/telegram.png' %}" alt="" class="header-socials__image">
                </a>
            </div>
            <p class="header-info__slogan">
                Машинная вышивка любой сложности
            </p>
            <a href="" class="header-info__email">
                info@majestic.ru
            </a>
        </div>
    </div>
</header>

majestic/templates/majestic/index.html
{% extends 'majestic/base.html' %}
{% load static %}


{% block meta_tags %}

{% endblock %}

{% block title %}
<title>
    Нижегородская вышивальная компания «Majestic»
</title>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'majestic/css/index.min.css' %}">
<link rel="stylesheet" href="{% static 'majestic/css/services.min.css' %}">
{% endblock %}


{% block content %}
<section class="intro content__intro">
    <h1 class="intro__title">
        <span>Машинная вышивка</span>
        в&nbsp;Нижнем Новгороде
    </h1>
    <p class="intro__text">
        Наносим рисунки на&nbsp;крой и&nbsp;текстильные изделия, используя современное оборудование, которое позволяет выполнять заказы быстро и&nbsp;качественно.
    </p>
    <a href="{% url 'majestic:services' %}" class="intro__btn _btn _btn--primary">
        Посмотреть услуги
    </a>
</section>
<!-- / end of intro -->

<section class="advantage content__advantage">
    <div class="advantage-item advantage__item">
        <div class="advantage-item__icon">
            <svg viewBox="0 0 420 420" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M210 329C275.722 329 329 275.722 329 210C329 144.278 275.722 91 210 91C144.278 91 91 144.278 91 210C91 275.722 144.278 329 210 329Z"
                    stroke-width="18" stroke-miterlimit="10" />
                <path
                    d="M46.91 116L46 162.75C45.9731 164.222 45.5406 165.658 44.75 166.9L20.65 204.83C19.8526 206.084 19.42 207.534 19.4006 209.02C19.3812 210.505 19.7757 211.966 20.54 213.24L43.78 252C44.5739 253.334 44.9663 254.869 44.91 256.42L43.19 301.98C43.1324 303.494 43.506 304.994 44.2672 306.304C45.0284 307.614 46.146 308.681 47.49 309.38L88.56 330.77C90.1398 331.593 91.3996 332.92 92.14 334.54L109.82 373.27C110.469 374.688 111.517 375.885 112.837 376.715C114.157 377.545 115.691 377.97 117.25 377.94L163.81 377.08C165.242 377.041 166.657 377.386 167.91 378.08L206 399.74C207.216 400.442 208.596 400.812 210 400.812C211.404 400.812 212.784 400.442 214 399.74L253.21 377C254.387 376.328 255.714 375.96 257.07 375.93L305.36 375.05C306.769 375.025 308.147 374.628 309.353 373.899C310.559 373.17 311.552 372.136 312.23 370.9L332 334.82C332.657 333.629 333.603 332.621 334.75 331.89L375.09 306.47C376.28 305.721 377.252 304.67 377.906 303.426C378.561 302.181 378.876 300.786 378.82 299.38L377.09 256.25C377.028 254.778 377.374 253.318 378.09 252.03L398.87 214.81C399.521 213.641 399.869 212.327 399.881 210.989C399.894 209.651 399.57 208.331 398.94 207.15L376.94 165.76C376.323 164.603 376 163.312 376 162V118.48C376 117.112 375.648 115.766 374.98 114.572C374.311 113.378 373.347 112.375 372.18 111.66L333.77 88.0902C332.61 87.3705 331.65 86.3695 330.98 85.1802L311.19 49.9102C310.52 48.7163 309.555 47.7142 308.387 46.9998C307.22 46.2855 305.888 45.8827 304.52 45.8302L257.77 44.0702C256.607 44.0267 255.467 43.7298 254.43 43.2002L214.94 23.0002C213.734 22.3832 212.391 22.0825 211.038 22.1262C209.684 22.17 208.363 22.5567 207.2 23.2502L171.11 44.7502C169.733 45.5621 168.146 45.9483 166.55 45.8602L122.21 43.3002C120.661 43.212 119.119 43.5763 117.773 44.3487C116.428 45.121 115.335 46.2681 114.63 47.6502L94.27 87.5202C93.4475 89.129 92.1046 90.4119 90.46 91.1602L51.58 108.91C50.2147 109.535 49.0527 110.531 48.2269 111.785C47.4011 113.038 46.9447 114.499 46.91 116Z"
                    stroke="black" stroke-width="18" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M159 204L195 241L263 178" stroke-width="18" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
        </div>
        <p class="advantage-item__text">
            Высококачественные расходные материалы
        </p>
    </div>
    <div class="advantage-item advantage__item">
        <div class="advantage-item__icon">
            <svg width="512" height="512" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M336.546 142.207L376.115 144.316C381.648 144.612 386.989 146.429 391.544 149.564C396.099 152.699 399.688 157.03 401.912 162.073L428.7 222.824C428.941 223.387 429.04 224 428.986 224.609C428.932 225.218 428.727 225.805 428.391 226.317C428.054 226.829 427.596 227.25 427.056 227.544C426.516 227.837 425.912 227.994 425.296 228H351.506C347.538 228 343.733 226.434 340.928 223.645C338.122 220.857 336.546 217.076 336.546 213.133V137.867C336.546 133.924 334.97 130.143 332.164 127.355C329.359 124.566 325.553 123 321.586 123H143"
                    stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M143 355H189" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M260 355H346" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path
                    d="M419 355H446.067C450.027 355 453.826 353.426 456.626 350.624C459.427 347.822 461 344.021 461 340.059V265.726C461 262.661 460.371 259.629 459.152 256.816C457.934 254.004 456.152 251.471 453.916 249.375L431.133 228"
                    stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path
                    d="M224.5 390C244.106 390 260 374.33 260 355C260 335.67 244.106 320 224.5 320C204.894 320 189 335.67 189 355C189 374.33 204.894 390 224.5 390Z"
                    stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path
                    d="M383.5 390C403.106 390 419 374.33 419 355C419 335.67 403.106 320 383.5 320C363.894 320 348 335.67 348 355C348 374.33 363.894 390 383.5 390Z"
                    stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M61 239H207" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M99 182H200" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M83 297H152" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
        </div>
        <p class="advantage-item__text">
            Доставка в любой регион России или СНГ
        </p>
    </div>
    <div class="advantage-item advantage__item">
        <div class="advantage-item__icon">
            <svg viewBox="0 0 420 420" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M112 181C129.673 181 144 166.673 144 149C144 131.327 129.673 117 112 117C94.3269 117 80 131.327 80 149C80 166.673 94.3269 181 112 181Z"
                    stroke-width="18" stroke-miterlimit="10" />
                <path
                    d="M210 129C227.673 129 242 114.673 242 97C242 79.3269 227.673 65 210 65C192.327 65 178 79.3269 178 97C178 114.673 192.327 129 210 129Z"
                    stroke-width="18" stroke-miterlimit="10" />
                <path
                    d="M308 176C325.673 176 340 161.673 340 144C340 126.327 325.673 112 308 112C290.327 112 276 126.327 276 144C276 161.673 290.327 176 308 176Z"
                    stroke-width="18" stroke-miterlimit="10" />
                <path
                    d="M308 282C325.673 282 340 267.673 340 250C340 232.327 325.673 218 308 218C290.327 218 276 232.327 276 250C276 267.673 290.327 282 308 282Z"
                    stroke-width="18" stroke-miterlimit="10" />
                <path
                    d="M66.9044 270.101C52.2219 258.06 41.1314 242.215 34.8441 224.299C28.5569 206.383 27.3146 187.084 31.2531 168.51C40.5252 124.337 72.7574 49.583 183.884 30.9496C344.396 4.03076 391 120.918 391 193.517C391 228.721 372.363 429.586 180.778 387.14C180.778 387.14 154.885 379.886 171.506 364.358C188.775 348.135 199.194 327.276 188.08 308.446C174.612 285.664 143.515 309.732 74.4959 274.98C71.9732 273.708 69.5918 272.174 67.3912 270.403L66.9044 270.101Z"
                    stroke-width="20" stroke-miterlimit="10" />
            </svg>
        </div>
        <p class="advantage-item__text">
            Широкая цветовая палитра для ваших заказов
        </p>
    </div>
</section>
<!-- / end of advantage -->

<section class="about content__about">
    <h2 class="about__title">
        О&nbsp;нашей компании
    </h2>
    <p class="about__text">
        Мы занимаемся нанесением логотипов на&nbsp;готовые или текстильные изделия и&nbsp;крой при&nbsp;помощи современного вышивального оборудования. Наша компания «Majestic» работает с&nbsp;2018 года. За 4 года мы смогли добиться неплохих результатов, но&nbsp;не&nbsp;стоим на&nbsp;месте, а&nbsp;продолжаем постоянно совершенствовать качество своей работы и&nbsp;развивать новые направления, на&nbsp;благо наших Клиентов.
    </p>
</section>
<!-- / end of about -->

<section class="our-services content__our-services">
    <h2 class="our-services__title">
        Наши услуги
    </h2>
    <div class="services content__services our-services__cards">
        <a href="{% url 'majestic:vnkroe' %}" class="service services__item">
            <div class="service-upside service__upside">
                <img src="{% static 'majestic/img/services/vnkroe-bs.png' %}" alt="" class="service-upside__background">
                <p class="service-upside__text">
                    Перейти к описанию ->
                </p>
            </div>
            <div class="service-backside service__backside">
                <img src="{% static 'majestic/img/services/example.png' %}" alt="" class="service-backside__icon">
                <h4 class="service-backside__name">
                    Вышивка на крое
                </h4>
            </div>
        </a>
        <!-- / end of item -->

        <a href="{% url 'majestic:shevnash' %}" class="service services__item">
            <div class="service-upside service__upside">
                <img src="{% static 'majestic/img/services/shevnash-bs.png' %}" alt="" class="service-upside__background">
                <p class="service-upside__text">
                    Перейти к описанию ->
                </p>
            </div>
            <div class="service-backside service__backside">
                <img src="{% static 'majestic/img/services/example-2.png' %}" alt="" class="service-backside__icon">
                <h4 class="service-backside__name">
                    Шевроны и нашивки
                </h4>
            </div>
        </a>
        <!-- / end of item -->

        <a href="{% url 'majestic:vngotizd' %}" class="service services__item">
            <div class="service-upside service__upside">
                <img src="{% static 'majestic/img/services/vngotizd-bs.png' %}" alt="" class="service-upside__background">
                <p class="service-upside__text">
                    Перейти к описанию ->
                </p>
            </div>
            <div class="service-backside service__backside">
                <img src="{% static 'majestic/img/services/example-3.png' %}" alt="" class="service-backside__icon">
                <h4 class="service-backside__name">
                    Вышивка на готовых изделиях
                </h4>
            </div>
        </a>
        <!-- / end of item -->
    </div>
    <a href="{% url 'majestic:services' %}" class="our-services__btn _btn _btn--primary">
        Открыть услуги
    </a>
</section>
<!-- / end of services -->
{% endblock %}

majestic/templates/majestic/services.html
{% extends 'majestic/base.html' %}
{% load static %}


{% block meta_tags %}

{% endblock %}

{% block title %}
<title>
    Услуги вышивальной компании «Majestic»
</title>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'majestic/css/services.min.css' %}">
{% endblock %}


{% block content %}
<div class="page-headings content__headings">
    <h1 class="page-title page-headings__title">
        Чем мы занимаемся
    </h1>
</div>
<!-- / end of page headings -->

<section class="services content__services">
    <a href="{% url 'majestic:vnkroe' %}" class="service services__item">
        <div class="service-upside service__upside">
            <img src="{% static 'majestic/img/services/vnkroe-bs.png' %}" alt="" class="service-upside__background">
            <p class="service-upside__text">
                Перейти к описанию ->
            </p>
        </div>
        <div class="service-backside service__backside">
            <img src="{% static 'majestic/img/services/example.png' %}" alt="" class="service-backside__icon">
            <h4 class="service-backside__name">
                Вышивка на крое
            </h4>
        </div>
    </a>
    <!-- / end of item -->

    <a href="{% url 'majestic:shevnash' %}" class="service services__item">
        <div class="service-upside service__upside">
            <img src="{% static 'majestic/img/services/shevnash-bs.png' %}" alt="" class="service-upside__background">
            <p class="service-upside__text">
                Перейти к описанию ->
            </p>
        </div>
        <div class="service-backside service__backside">
            <img src="{% static 'majestic/img/services/example-2.png' %}" alt="" class="service-backside__icon">
            <h4 class="service-backside__name">
                Шевроны и нашивки
            </h4>
        </div>
    </a>
    <!-- / end of item -->

    <a href="{% url 'majestic:vngotizd' %}" class="service services__item">
        <div class="service-upside service__upside">
            <img src="{% static 'majestic/img/services/vngotizd-bs.png' %}" alt="" class="service-upside__background">
            <p class="service-upside__text">
                Перейти к описанию ->
            </p>
        </div>
        <div class="service-backside service__backside">
            <img src="{% static 'majestic/img/services/example-3.png' %}" alt="" class="service-backside__icon">
            <h4 class="service-backside__name">
                Вышивка на готовых изделиях
            </h4>
        </div>
    </a>
    <!-- / end of item -->

    <a href="{% url 'majestic:cerkvysh' %}" class="service services__item">
        <div class="service-upside service__upside">
            <img src="{% static 'majestic/img/services/cerkvysh-bs.png' %}" alt="" class="service-upside__background">
            <p class="service-upside__text">
                Перейти к описанию ->
            </p>
        </div>
        <div class="service-backside service__backside">
            <img src="{% static 'majestic/img/services/example-4.png' %}" alt="" class="service-backside__icon">
            <h4 class="service-backside__name">
                Церковная вышивка
            </h4>
        </div>
    </a>
    <!-- / end of item -->
</section>
<!-- / end of services -->
{% endblock %}

majestic/templates/majestic/services/base.html
{% extends 'majestic/base.html' %}
{% load static %}


{% block meta_tags %}

{% endblock %}

{% block title %}
<title>
    Услуги вышивальной компании «Majestic»
</title>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'majestic/css/service.min.css' %}">
<link rel="stylesheet" href="{% static 'majestic/css/price.min.css' %}">
{% endblock %}


{% block content %}
<div class="page-headings content__headings">
    <a href="{% url 'majestic:services' %}" class="page-subtitle page-headings__subtitle page-headings__subtitle--link">
        <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd"
                d="M10.7071 2.29289C11.0976 2.68342 11.0976 3.31658 10.7071 3.70711L6.41421 8L10.7071 12.2929C11.0976 12.6834 11.0976 13.3166 10.7071 13.7071C10.3166 14.0976 9.68342 14.0976 9.29289 13.7071L4.29289 8.70711C3.90237 8.31658 3.90237 7.68342 4.29289 7.29289L9.29289 2.29289C9.68342 1.90237 10.3166 1.90237 10.7071 2.29289Z" />
        </svg>
        Вернуться к услугам
    </a>
    <h1 class="page-title page-headings__title">
        {% block service_title %}
            Заголовок страницы
        {% endblock %}
    </h1>
</div>
<!-- / end of page headings -->

<section class="service-description content__service-description">
    <p class="service-description__text">
        {% block service_description %}
        {% endblock %}
    </p>
</section>
<!-- / end of page description -->

<h4 class="service-title content__service-title">
    Примеры наших работ
</h4>
<section class="service-examples content__service-examples">
    {% block service_images %}{% endblock %}
</section>
<!-- / end of examples -->

    {% block service_content %}
    {% endblock %}
{% endblock %}